/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DevManagerRouteImport } from './routes/dev-manager'
import { Route as DeveloperManagementRouteImport } from './routes/developer-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevManagerRoute = DevManagerRouteImport.update({
  id: '/dev-manager',
  path: '/dev-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperManagementRoute = DeveloperManagementRouteImport.update({
  id: '/developer-management',
  path: '/developer-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev-manager': typeof DevManagerRoute
  '/developer-management': typeof DeveloperManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev-manager': typeof DevManagerRoute
  '/developer-management': typeof DeveloperManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev-manager': typeof DevManagerRoute
  '/developer-management': typeof DeveloperManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/dev-manager' | '/developer-management'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dev-manager' | '/developer-management'
  id: '__root__' | '/' | '/auth' | '/dev-manager' | '/developer-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DevManagerRoute: typeof DevManagerRoute
  DeveloperManagementRoute: typeof DeveloperManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-manager': {
      id: '/dev-manager'
      path: '/dev-manager'
      fullPath: '/dev-manager'
      preLoaderRoute: typeof DevManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-management': {
      id: '/developer-management'
      path: '/developer-management'
      fullPath: '/developer-management'
      preLoaderRoute: typeof DeveloperManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DevManagerRoute: DevManagerRoute,
  DeveloperManagementRoute: DeveloperManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
